### ISSUE TITLE
Plugin overwrites existing content of legal pages. Is this a joke?

### ISSUE THREAD

**Issue by benlau87** [Magenerds/de_de#13]

**Comment by sydekumf** [comment]
Hi there,

as Magenerds_de_de is just a simple language file, I assume you used this module: https://github.com/Magenerds/GermanLaw
In the documentation you can read that the module installs cms pages: http://doc.magenerds.com/germanlaw/

> This extension installs 5 cms pages during installation:
> - AGB
> - Widerrufsbelehrung
> - Impressum
> - Versandkosten
> - Datenschutzbestimmung
> The cms pages have dummy content so you should fill them if you use them.

Before you install any extension or change something in your store, you should always back up the data or do a test installation on a test system. The extensions assume a certain precondition, as these extensions will often be installed in a fresh Magento installation.

As you did not ask for further help or changes I will close this issue. But of course feel free to open it again :-) Thanks!
