### ISSUE TITLE
Funktionaler Fehler bei Übersetzung

### ISSUE THREAD

**Issue by rorou** [Magenerds/de_de#5]
In der Zeile 7275 hat sich ein funktionaler Fehler eingeschlichen, der den eigentlichen Inhalt verfälscht bzw. nicht korrekt darstellt:

Faslch: The order was placed using %1.,Die Bestellung wurde aufgegeben mit 1%.
Richtig: The order was placed using %1.,Die Bestellung wurde aufgegeben mit %1.

Somit wird die Währung, in der die Bestellung getätigt wurde, richtig angezeigt.

**Comment by ghost** [comment]
Ist korrigiert, kann geschlossen werden
